trainer:
  load_from:
  save_path: checkpoints/test.safetensors
  checkpoint_path: checkpoints/
  checkpoint_epoch: 1        # checkpoint every n epochs
  checkpoint_step: 500       # 0: don't checkpoint
  end_step: 10
  end_epoch: 1

model:
  module: modules.dped.DPEDModel
  generator:
    module: modules.dped.DPEDGenerator
  discriminator:
    module: modules.discriminator.DPEDDiscriminator
  
  image_normalization:
    min: 0
    max: 1

criterion:
  module: modules.loss.DPEDLoss
  args:
    w_color: 0.1
    w_texture: 0.4
    w_content: 1.0
    w_total_variation: 400.0
    blur_sigma: 3
    blur_kernel_size: 21

hyperparameters:
  optimizer:
    name: torch.optim.AdamW
    args:
      lr: 3e-4
  batch_size: 20

dataset:
  module: data.patches.DPEDPatchDataset
  args:
    path: dataset/dped/blackberry/training_data
    input_label: blackberry
    target_label: canon
